#!/bin/bash
CONTAINER_LABEL=ros_$1

WORKDIR=$(pwd)
echo $WORKDIR
USER_HOME_PATH=$(pwd)/container/home/$USER
mkdir -p $USER_HOME_PATH
docker run -it --rm \
    --user $(id -u):$(id -g) \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --network="host" \
    --ipc="host" \
    --privileged \
    --oom-kill-disable \
    --volume="/etc/group:/etc/group:ro" \
    --volume="$USER_HOME_PATH:/home/$USER:rw" \
    --volume="/etc/passwd:/etc/passwd:ro" \
    --volume="/etc/shadow:/etc/shadow:ro" \
    --volume="/etc/sudoers.d:/etc/sudoers.d:ro" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    --volume="$WORKDIR:$WORKDIR:rw" \
    --name="$CONTAINER_LABEL" \
    --volume="/dev/shm:/dev/shm:rw" \
    --workdir="$WORKDIR" \
    --volume="/dev:/dev:rw" \
    ros-$1