# Use root/pass as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 33060:33060
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080